/*
API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: adapters
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package adaptersapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GlobalCustomAttributeUpdateApiModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GlobalCustomAttributeUpdateApiModel{}

// GlobalCustomAttributeUpdateApiModel struct for GlobalCustomAttributeUpdateApiModel
type GlobalCustomAttributeUpdateApiModel struct {
	// Name of attribute
	Name string `json:"name"`
	// Collection of attribute options   Available for attributes of type `options` and `multiple options` only
	Options []CustomAttributeOptionUpdateApiModel `json:"options,omitempty"`
	// Indicates whether the attribute is available
	IsEnabled NullableBool `json:"isEnabled,omitempty"`
	// Indicates whether the attribute value is mandatory to specify
	IsRequired NullableBool `json:"isRequired,omitempty"`
}

type _GlobalCustomAttributeUpdateApiModel GlobalCustomAttributeUpdateApiModel

// NewGlobalCustomAttributeUpdateApiModel instantiates a new GlobalCustomAttributeUpdateApiModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGlobalCustomAttributeUpdateApiModel(name string) *GlobalCustomAttributeUpdateApiModel {
	this := GlobalCustomAttributeUpdateApiModel{}
	this.Name = name
	return &this
}

// NewGlobalCustomAttributeUpdateApiModelWithDefaults instantiates a new GlobalCustomAttributeUpdateApiModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGlobalCustomAttributeUpdateApiModelWithDefaults() *GlobalCustomAttributeUpdateApiModel {
	this := GlobalCustomAttributeUpdateApiModel{}
	return &this
}

// GetName returns the Name field value
func (o *GlobalCustomAttributeUpdateApiModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GlobalCustomAttributeUpdateApiModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GlobalCustomAttributeUpdateApiModel) SetName(v string) {
	o.Name = v
}

// GetOptions returns the Options field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GlobalCustomAttributeUpdateApiModel) GetOptions() []CustomAttributeOptionUpdateApiModel {
	if o == nil {
		var ret []CustomAttributeOptionUpdateApiModel
		return ret
	}
	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GlobalCustomAttributeUpdateApiModel) GetOptionsOk() ([]CustomAttributeOptionUpdateApiModel, bool) {
	if o == nil || IsNil(o.Options) {
		return nil, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *GlobalCustomAttributeUpdateApiModel) HasOptions() bool {
	if o != nil && !IsNil(o.Options) {
		return true
	}

	return false
}

// SetOptions gets a reference to the given []CustomAttributeOptionUpdateApiModel and assigns it to the Options field.
func (o *GlobalCustomAttributeUpdateApiModel) SetOptions(v []CustomAttributeOptionUpdateApiModel) {
	o.Options = v
}

// GetIsEnabled returns the IsEnabled field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GlobalCustomAttributeUpdateApiModel) GetIsEnabled() bool {
	if o == nil || IsNil(o.IsEnabled.Get()) {
		var ret bool
		return ret
	}
	return *o.IsEnabled.Get()
}

// GetIsEnabledOk returns a tuple with the IsEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GlobalCustomAttributeUpdateApiModel) GetIsEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsEnabled.Get(), o.IsEnabled.IsSet()
}

// HasIsEnabled returns a boolean if a field has been set.
func (o *GlobalCustomAttributeUpdateApiModel) HasIsEnabled() bool {
	if o != nil && o.IsEnabled.IsSet() {
		return true
	}

	return false
}

// SetIsEnabled gets a reference to the given NullableBool and assigns it to the IsEnabled field.
func (o *GlobalCustomAttributeUpdateApiModel) SetIsEnabled(v bool) {
	o.IsEnabled.Set(&v)
}
// SetIsEnabledNil sets the value for IsEnabled to be an explicit nil
func (o *GlobalCustomAttributeUpdateApiModel) SetIsEnabledNil() {
	o.IsEnabled.Set(nil)
}

// UnsetIsEnabled ensures that no value is present for IsEnabled, not even an explicit nil
func (o *GlobalCustomAttributeUpdateApiModel) UnsetIsEnabled() {
	o.IsEnabled.Unset()
}

// GetIsRequired returns the IsRequired field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GlobalCustomAttributeUpdateApiModel) GetIsRequired() bool {
	if o == nil || IsNil(o.IsRequired.Get()) {
		var ret bool
		return ret
	}
	return *o.IsRequired.Get()
}

// GetIsRequiredOk returns a tuple with the IsRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GlobalCustomAttributeUpdateApiModel) GetIsRequiredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsRequired.Get(), o.IsRequired.IsSet()
}

// HasIsRequired returns a boolean if a field has been set.
func (o *GlobalCustomAttributeUpdateApiModel) HasIsRequired() bool {
	if o != nil && o.IsRequired.IsSet() {
		return true
	}

	return false
}

// SetIsRequired gets a reference to the given NullableBool and assigns it to the IsRequired field.
func (o *GlobalCustomAttributeUpdateApiModel) SetIsRequired(v bool) {
	o.IsRequired.Set(&v)
}
// SetIsRequiredNil sets the value for IsRequired to be an explicit nil
func (o *GlobalCustomAttributeUpdateApiModel) SetIsRequiredNil() {
	o.IsRequired.Set(nil)
}

// UnsetIsRequired ensures that no value is present for IsRequired, not even an explicit nil
func (o *GlobalCustomAttributeUpdateApiModel) UnsetIsRequired() {
	o.IsRequired.Unset()
}

func (o GlobalCustomAttributeUpdateApiModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GlobalCustomAttributeUpdateApiModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if o.Options != nil {
		toSerialize["options"] = o.Options
	}
	if o.IsEnabled.IsSet() {
		toSerialize["isEnabled"] = o.IsEnabled.Get()
	}
	if o.IsRequired.IsSet() {
		toSerialize["isRequired"] = o.IsRequired.Get()
	}
	return toSerialize, nil
}

func (o *GlobalCustomAttributeUpdateApiModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGlobalCustomAttributeUpdateApiModel := _GlobalCustomAttributeUpdateApiModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGlobalCustomAttributeUpdateApiModel)

	if err != nil {
		return err
	}

	*o = GlobalCustomAttributeUpdateApiModel(varGlobalCustomAttributeUpdateApiModel)

	return err
}

type NullableGlobalCustomAttributeUpdateApiModel struct {
	value *GlobalCustomAttributeUpdateApiModel
	isSet bool
}

func (v NullableGlobalCustomAttributeUpdateApiModel) Get() *GlobalCustomAttributeUpdateApiModel {
	return v.value
}

func (v *NullableGlobalCustomAttributeUpdateApiModel) Set(val *GlobalCustomAttributeUpdateApiModel) {
	v.value = val
	v.isSet = true
}

func (v NullableGlobalCustomAttributeUpdateApiModel) IsSet() bool {
	return v.isSet
}

func (v *NullableGlobalCustomAttributeUpdateApiModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGlobalCustomAttributeUpdateApiModel(val *GlobalCustomAttributeUpdateApiModel) *NullableGlobalCustomAttributeUpdateApiModel {
	return &NullableGlobalCustomAttributeUpdateApiModel{value: val, isSet: true}
}

func (v NullableGlobalCustomAttributeUpdateApiModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGlobalCustomAttributeUpdateApiModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


