/*
API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: adapters
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package adaptersapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CustomAttributeOptionPostApiModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomAttributeOptionPostApiModel{}

// CustomAttributeOptionPostApiModel struct for CustomAttributeOptionPostApiModel
type CustomAttributeOptionPostApiModel struct {
	// Value of the attribute option
	Value NullableString `json:"value,omitempty"`
	// Indicates if the attribute option is used by default
	IsDefault bool `json:"isDefault"`
}

type _CustomAttributeOptionPostApiModel CustomAttributeOptionPostApiModel

// NewCustomAttributeOptionPostApiModel instantiates a new CustomAttributeOptionPostApiModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomAttributeOptionPostApiModel(isDefault bool) *CustomAttributeOptionPostApiModel {
	this := CustomAttributeOptionPostApiModel{}
	this.IsDefault = isDefault
	return &this
}

// NewCustomAttributeOptionPostApiModelWithDefaults instantiates a new CustomAttributeOptionPostApiModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomAttributeOptionPostApiModelWithDefaults() *CustomAttributeOptionPostApiModel {
	this := CustomAttributeOptionPostApiModel{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomAttributeOptionPostApiModel) GetValue() string {
	if o == nil || IsNil(o.Value.Get()) {
		var ret string
		return ret
	}
	return *o.Value.Get()
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomAttributeOptionPostApiModel) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value.Get(), o.Value.IsSet()
}

// HasValue returns a boolean if a field has been set.
func (o *CustomAttributeOptionPostApiModel) HasValue() bool {
	if o != nil && o.Value.IsSet() {
		return true
	}

	return false
}

// SetValue gets a reference to the given NullableString and assigns it to the Value field.
func (o *CustomAttributeOptionPostApiModel) SetValue(v string) {
	o.Value.Set(&v)
}
// SetValueNil sets the value for Value to be an explicit nil
func (o *CustomAttributeOptionPostApiModel) SetValueNil() {
	o.Value.Set(nil)
}

// UnsetValue ensures that no value is present for Value, not even an explicit nil
func (o *CustomAttributeOptionPostApiModel) UnsetValue() {
	o.Value.Unset()
}

// GetIsDefault returns the IsDefault field value
func (o *CustomAttributeOptionPostApiModel) GetIsDefault() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsDefault
}

// GetIsDefaultOk returns a tuple with the IsDefault field value
// and a boolean to check if the value has been set.
func (o *CustomAttributeOptionPostApiModel) GetIsDefaultOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsDefault, true
}

// SetIsDefault sets field value
func (o *CustomAttributeOptionPostApiModel) SetIsDefault(v bool) {
	o.IsDefault = v
}

func (o CustomAttributeOptionPostApiModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomAttributeOptionPostApiModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Value.IsSet() {
		toSerialize["value"] = o.Value.Get()
	}
	toSerialize["isDefault"] = o.IsDefault
	return toSerialize, nil
}

func (o *CustomAttributeOptionPostApiModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"isDefault",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCustomAttributeOptionPostApiModel := _CustomAttributeOptionPostApiModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCustomAttributeOptionPostApiModel)

	if err != nil {
		return err
	}

	*o = CustomAttributeOptionPostApiModel(varCustomAttributeOptionPostApiModel)

	return err
}

type NullableCustomAttributeOptionPostApiModel struct {
	value *CustomAttributeOptionPostApiModel
	isSet bool
}

func (v NullableCustomAttributeOptionPostApiModel) Get() *CustomAttributeOptionPostApiModel {
	return v.value
}

func (v *NullableCustomAttributeOptionPostApiModel) Set(val *CustomAttributeOptionPostApiModel) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomAttributeOptionPostApiModel) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomAttributeOptionPostApiModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomAttributeOptionPostApiModel(val *CustomAttributeOptionPostApiModel) *NullableCustomAttributeOptionPostApiModel {
	return &NullableCustomAttributeOptionPostApiModel{value: val, isSet: true}
}

func (v NullableCustomAttributeOptionPostApiModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomAttributeOptionPostApiModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


