/*
API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: adapters
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package adaptersapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CustomAttributeOptionUpdateApiModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomAttributeOptionUpdateApiModel{}

// CustomAttributeOptionUpdateApiModel struct for CustomAttributeOptionUpdateApiModel
type CustomAttributeOptionUpdateApiModel struct {
	// Unique ID of the attribute option
	Id string `json:"id"`
	// Value of the attribute option
	Value NullableString `json:"value,omitempty"`
	// Indicates if the attribute option is used by default
	IsDefault bool `json:"isDefault"`
	// Indicates if the attributes option is deleted
	IsDeleted bool `json:"isDeleted"`
}

type _CustomAttributeOptionUpdateApiModel CustomAttributeOptionUpdateApiModel

// NewCustomAttributeOptionUpdateApiModel instantiates a new CustomAttributeOptionUpdateApiModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomAttributeOptionUpdateApiModel(id string, isDefault bool, isDeleted bool) *CustomAttributeOptionUpdateApiModel {
	this := CustomAttributeOptionUpdateApiModel{}
	this.Id = id
	this.IsDefault = isDefault
	this.IsDeleted = isDeleted
	return &this
}

// NewCustomAttributeOptionUpdateApiModelWithDefaults instantiates a new CustomAttributeOptionUpdateApiModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomAttributeOptionUpdateApiModelWithDefaults() *CustomAttributeOptionUpdateApiModel {
	this := CustomAttributeOptionUpdateApiModel{}
	return &this
}

// GetId returns the Id field value
func (o *CustomAttributeOptionUpdateApiModel) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CustomAttributeOptionUpdateApiModel) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CustomAttributeOptionUpdateApiModel) SetId(v string) {
	o.Id = v
}

// GetValue returns the Value field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomAttributeOptionUpdateApiModel) GetValue() string {
	if o == nil || IsNil(o.Value.Get()) {
		var ret string
		return ret
	}
	return *o.Value.Get()
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomAttributeOptionUpdateApiModel) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Value.Get(), o.Value.IsSet()
}

// HasValue returns a boolean if a field has been set.
func (o *CustomAttributeOptionUpdateApiModel) HasValue() bool {
	if o != nil && o.Value.IsSet() {
		return true
	}

	return false
}

// SetValue gets a reference to the given NullableString and assigns it to the Value field.
func (o *CustomAttributeOptionUpdateApiModel) SetValue(v string) {
	o.Value.Set(&v)
}
// SetValueNil sets the value for Value to be an explicit nil
func (o *CustomAttributeOptionUpdateApiModel) SetValueNil() {
	o.Value.Set(nil)
}

// UnsetValue ensures that no value is present for Value, not even an explicit nil
func (o *CustomAttributeOptionUpdateApiModel) UnsetValue() {
	o.Value.Unset()
}

// GetIsDefault returns the IsDefault field value
func (o *CustomAttributeOptionUpdateApiModel) GetIsDefault() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsDefault
}

// GetIsDefaultOk returns a tuple with the IsDefault field value
// and a boolean to check if the value has been set.
func (o *CustomAttributeOptionUpdateApiModel) GetIsDefaultOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsDefault, true
}

// SetIsDefault sets field value
func (o *CustomAttributeOptionUpdateApiModel) SetIsDefault(v bool) {
	o.IsDefault = v
}

// GetIsDeleted returns the IsDeleted field value
func (o *CustomAttributeOptionUpdateApiModel) GetIsDeleted() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsDeleted
}

// GetIsDeletedOk returns a tuple with the IsDeleted field value
// and a boolean to check if the value has been set.
func (o *CustomAttributeOptionUpdateApiModel) GetIsDeletedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsDeleted, true
}

// SetIsDeleted sets field value
func (o *CustomAttributeOptionUpdateApiModel) SetIsDeleted(v bool) {
	o.IsDeleted = v
}

func (o CustomAttributeOptionUpdateApiModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomAttributeOptionUpdateApiModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if o.Value.IsSet() {
		toSerialize["value"] = o.Value.Get()
	}
	toSerialize["isDefault"] = o.IsDefault
	toSerialize["isDeleted"] = o.IsDeleted
	return toSerialize, nil
}

func (o *CustomAttributeOptionUpdateApiModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"isDefault",
		"isDeleted",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCustomAttributeOptionUpdateApiModel := _CustomAttributeOptionUpdateApiModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCustomAttributeOptionUpdateApiModel)

	if err != nil {
		return err
	}

	*o = CustomAttributeOptionUpdateApiModel(varCustomAttributeOptionUpdateApiModel)

	return err
}

type NullableCustomAttributeOptionUpdateApiModel struct {
	value *CustomAttributeOptionUpdateApiModel
	isSet bool
}

func (v NullableCustomAttributeOptionUpdateApiModel) Get() *CustomAttributeOptionUpdateApiModel {
	return v.value
}

func (v *NullableCustomAttributeOptionUpdateApiModel) Set(val *CustomAttributeOptionUpdateApiModel) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomAttributeOptionUpdateApiModel) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomAttributeOptionUpdateApiModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomAttributeOptionUpdateApiModel(val *CustomAttributeOptionUpdateApiModel) *NullableCustomAttributeOptionUpdateApiModel {
	return &NullableCustomAttributeOptionUpdateApiModel{value: val, isSet: true}
}

func (v NullableCustomAttributeOptionUpdateApiModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomAttributeOptionUpdateApiModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


