/*
API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: adapters
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package adaptersapi

import (
	"encoding/json"
)

// checks if the WorkItemFilterApiModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkItemFilterApiModel{}

// WorkItemFilterApiModel struct for WorkItemFilterApiModel
type WorkItemFilterApiModel struct {
	// Name or identifier (UUID) of work item
	NameOrId NullableString `json:"nameOrId,omitempty"`
	// Collection of identifiers of work items which need to be included in result regardless of filtering
	IncludeIds []string `json:"includeIds,omitempty"`
	// Collection of identifiers of work items which need to be excluded from result regardless of filtering
	ExcludeIds []string `json:"excludeIds,omitempty"`
	// Collection of project identifiers
	ProjectIds []string `json:"projectIds,omitempty"`
	// Name of work item
	Name NullableString `json:"name,omitempty"`
	// Specifies a work item unique IDs to search for
	Ids []string `json:"ids,omitempty"`
	// Collection of global (integer) identifiers
	GlobalIds []int64 `json:"globalIds,omitempty"`
	// Custom attributes of work item
	Attributes map[string][]string `json:"attributes,omitempty"`
	// Is result must consist of only actual/deleted work items
	IsDeleted NullableBool `json:"isDeleted,omitempty"`
	// Collection of section identifiers
	SectionIds []string `json:"sectionIds,omitempty"`
	// Collection of states of work item
	States []WorkItemStates `json:"states,omitempty"`
	// Collection of priorities of work item
	Priorities []WorkItemPriorityModel `json:"priorities,omitempty"`
	// Source type of work item (manual creation or AI generated)
	SourceTypes []WorkItemSourceTypeModel `json:"sourceTypes,omitempty"`
	// Collection of types of work item
	Types []WorkItemTypeModel `json:"types,omitempty"`
	// Specifies a work item duration range to search for
	Duration NullableInt32RangeSelectorModel `json:"duration,omitempty"`
	// Is result must consist of only manual/automated work items
	IsAutomated NullableBool `json:"isAutomated,omitempty"`
	// Collection of tags
	Tags []string `json:"tags,omitempty"`
	// Collection of tags to exclude
	ExcludeTags []string `json:"excludeTags,omitempty"`
	// Collection of identifiers of linked autotests
	AutoTestIds []string `json:"autoTestIds,omitempty"`
}

// NewWorkItemFilterApiModel instantiates a new WorkItemFilterApiModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkItemFilterApiModel() *WorkItemFilterApiModel {
	this := WorkItemFilterApiModel{}
	return &this
}

// NewWorkItemFilterApiModelWithDefaults instantiates a new WorkItemFilterApiModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkItemFilterApiModelWithDefaults() *WorkItemFilterApiModel {
	this := WorkItemFilterApiModel{}
	return &this
}

// GetNameOrId returns the NameOrId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkItemFilterApiModel) GetNameOrId() string {
	if o == nil || IsNil(o.NameOrId.Get()) {
		var ret string
		return ret
	}
	return *o.NameOrId.Get()
}

// GetNameOrIdOk returns a tuple with the NameOrId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkItemFilterApiModel) GetNameOrIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NameOrId.Get(), o.NameOrId.IsSet()
}

// HasNameOrId returns a boolean if a field has been set.
func (o *WorkItemFilterApiModel) HasNameOrId() bool {
	if o != nil && o.NameOrId.IsSet() {
		return true
	}

	return false
}

// SetNameOrId gets a reference to the given NullableString and assigns it to the NameOrId field.
func (o *WorkItemFilterApiModel) SetNameOrId(v string) {
	o.NameOrId.Set(&v)
}
// SetNameOrIdNil sets the value for NameOrId to be an explicit nil
func (o *WorkItemFilterApiModel) SetNameOrIdNil() {
	o.NameOrId.Set(nil)
}

// UnsetNameOrId ensures that no value is present for NameOrId, not even an explicit nil
func (o *WorkItemFilterApiModel) UnsetNameOrId() {
	o.NameOrId.Unset()
}

// GetIncludeIds returns the IncludeIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkItemFilterApiModel) GetIncludeIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.IncludeIds
}

// GetIncludeIdsOk returns a tuple with the IncludeIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkItemFilterApiModel) GetIncludeIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.IncludeIds) {
		return nil, false
	}
	return o.IncludeIds, true
}

// HasIncludeIds returns a boolean if a field has been set.
func (o *WorkItemFilterApiModel) HasIncludeIds() bool {
	if o != nil && !IsNil(o.IncludeIds) {
		return true
	}

	return false
}

// SetIncludeIds gets a reference to the given []string and assigns it to the IncludeIds field.
func (o *WorkItemFilterApiModel) SetIncludeIds(v []string) {
	o.IncludeIds = v
}

// GetExcludeIds returns the ExcludeIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkItemFilterApiModel) GetExcludeIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.ExcludeIds
}

// GetExcludeIdsOk returns a tuple with the ExcludeIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkItemFilterApiModel) GetExcludeIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.ExcludeIds) {
		return nil, false
	}
	return o.ExcludeIds, true
}

// HasExcludeIds returns a boolean if a field has been set.
func (o *WorkItemFilterApiModel) HasExcludeIds() bool {
	if o != nil && !IsNil(o.ExcludeIds) {
		return true
	}

	return false
}

// SetExcludeIds gets a reference to the given []string and assigns it to the ExcludeIds field.
func (o *WorkItemFilterApiModel) SetExcludeIds(v []string) {
	o.ExcludeIds = v
}

// GetProjectIds returns the ProjectIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkItemFilterApiModel) GetProjectIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.ProjectIds
}

// GetProjectIdsOk returns a tuple with the ProjectIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkItemFilterApiModel) GetProjectIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.ProjectIds) {
		return nil, false
	}
	return o.ProjectIds, true
}

// HasProjectIds returns a boolean if a field has been set.
func (o *WorkItemFilterApiModel) HasProjectIds() bool {
	if o != nil && !IsNil(o.ProjectIds) {
		return true
	}

	return false
}

// SetProjectIds gets a reference to the given []string and assigns it to the ProjectIds field.
func (o *WorkItemFilterApiModel) SetProjectIds(v []string) {
	o.ProjectIds = v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkItemFilterApiModel) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkItemFilterApiModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *WorkItemFilterApiModel) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *WorkItemFilterApiModel) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *WorkItemFilterApiModel) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *WorkItemFilterApiModel) UnsetName() {
	o.Name.Unset()
}

// GetIds returns the Ids field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkItemFilterApiModel) GetIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Ids
}

// GetIdsOk returns a tuple with the Ids field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkItemFilterApiModel) GetIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.Ids) {
		return nil, false
	}
	return o.Ids, true
}

// HasIds returns a boolean if a field has been set.
func (o *WorkItemFilterApiModel) HasIds() bool {
	if o != nil && !IsNil(o.Ids) {
		return true
	}

	return false
}

// SetIds gets a reference to the given []string and assigns it to the Ids field.
func (o *WorkItemFilterApiModel) SetIds(v []string) {
	o.Ids = v
}

// GetGlobalIds returns the GlobalIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkItemFilterApiModel) GetGlobalIds() []int64 {
	if o == nil {
		var ret []int64
		return ret
	}
	return o.GlobalIds
}

// GetGlobalIdsOk returns a tuple with the GlobalIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkItemFilterApiModel) GetGlobalIdsOk() ([]int64, bool) {
	if o == nil || IsNil(o.GlobalIds) {
		return nil, false
	}
	return o.GlobalIds, true
}

// HasGlobalIds returns a boolean if a field has been set.
func (o *WorkItemFilterApiModel) HasGlobalIds() bool {
	if o != nil && !IsNil(o.GlobalIds) {
		return true
	}

	return false
}

// SetGlobalIds gets a reference to the given []int64 and assigns it to the GlobalIds field.
func (o *WorkItemFilterApiModel) SetGlobalIds(v []int64) {
	o.GlobalIds = v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkItemFilterApiModel) GetAttributes() map[string][]string {
	if o == nil {
		var ret map[string][]string
		return ret
	}
	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkItemFilterApiModel) GetAttributesOk() (*map[string][]string, bool) {
	if o == nil || IsNil(o.Attributes) {
		return nil, false
	}
	return &o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *WorkItemFilterApiModel) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given map[string][]string and assigns it to the Attributes field.
func (o *WorkItemFilterApiModel) SetAttributes(v map[string][]string) {
	o.Attributes = v
}

// GetIsDeleted returns the IsDeleted field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkItemFilterApiModel) GetIsDeleted() bool {
	if o == nil || IsNil(o.IsDeleted.Get()) {
		var ret bool
		return ret
	}
	return *o.IsDeleted.Get()
}

// GetIsDeletedOk returns a tuple with the IsDeleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkItemFilterApiModel) GetIsDeletedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsDeleted.Get(), o.IsDeleted.IsSet()
}

// HasIsDeleted returns a boolean if a field has been set.
func (o *WorkItemFilterApiModel) HasIsDeleted() bool {
	if o != nil && o.IsDeleted.IsSet() {
		return true
	}

	return false
}

// SetIsDeleted gets a reference to the given NullableBool and assigns it to the IsDeleted field.
func (o *WorkItemFilterApiModel) SetIsDeleted(v bool) {
	o.IsDeleted.Set(&v)
}
// SetIsDeletedNil sets the value for IsDeleted to be an explicit nil
func (o *WorkItemFilterApiModel) SetIsDeletedNil() {
	o.IsDeleted.Set(nil)
}

// UnsetIsDeleted ensures that no value is present for IsDeleted, not even an explicit nil
func (o *WorkItemFilterApiModel) UnsetIsDeleted() {
	o.IsDeleted.Unset()
}

// GetSectionIds returns the SectionIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkItemFilterApiModel) GetSectionIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.SectionIds
}

// GetSectionIdsOk returns a tuple with the SectionIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkItemFilterApiModel) GetSectionIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.SectionIds) {
		return nil, false
	}
	return o.SectionIds, true
}

// HasSectionIds returns a boolean if a field has been set.
func (o *WorkItemFilterApiModel) HasSectionIds() bool {
	if o != nil && !IsNil(o.SectionIds) {
		return true
	}

	return false
}

// SetSectionIds gets a reference to the given []string and assigns it to the SectionIds field.
func (o *WorkItemFilterApiModel) SetSectionIds(v []string) {
	o.SectionIds = v
}

// GetStates returns the States field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkItemFilterApiModel) GetStates() []WorkItemStates {
	if o == nil {
		var ret []WorkItemStates
		return ret
	}
	return o.States
}

// GetStatesOk returns a tuple with the States field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkItemFilterApiModel) GetStatesOk() ([]WorkItemStates, bool) {
	if o == nil || IsNil(o.States) {
		return nil, false
	}
	return o.States, true
}

// HasStates returns a boolean if a field has been set.
func (o *WorkItemFilterApiModel) HasStates() bool {
	if o != nil && !IsNil(o.States) {
		return true
	}

	return false
}

// SetStates gets a reference to the given []WorkItemStates and assigns it to the States field.
func (o *WorkItemFilterApiModel) SetStates(v []WorkItemStates) {
	o.States = v
}

// GetPriorities returns the Priorities field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkItemFilterApiModel) GetPriorities() []WorkItemPriorityModel {
	if o == nil {
		var ret []WorkItemPriorityModel
		return ret
	}
	return o.Priorities
}

// GetPrioritiesOk returns a tuple with the Priorities field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkItemFilterApiModel) GetPrioritiesOk() ([]WorkItemPriorityModel, bool) {
	if o == nil || IsNil(o.Priorities) {
		return nil, false
	}
	return o.Priorities, true
}

// HasPriorities returns a boolean if a field has been set.
func (o *WorkItemFilterApiModel) HasPriorities() bool {
	if o != nil && !IsNil(o.Priorities) {
		return true
	}

	return false
}

// SetPriorities gets a reference to the given []WorkItemPriorityModel and assigns it to the Priorities field.
func (o *WorkItemFilterApiModel) SetPriorities(v []WorkItemPriorityModel) {
	o.Priorities = v
}

// GetSourceTypes returns the SourceTypes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkItemFilterApiModel) GetSourceTypes() []WorkItemSourceTypeModel {
	if o == nil {
		var ret []WorkItemSourceTypeModel
		return ret
	}
	return o.SourceTypes
}

// GetSourceTypesOk returns a tuple with the SourceTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkItemFilterApiModel) GetSourceTypesOk() ([]WorkItemSourceTypeModel, bool) {
	if o == nil || IsNil(o.SourceTypes) {
		return nil, false
	}
	return o.SourceTypes, true
}

// HasSourceTypes returns a boolean if a field has been set.
func (o *WorkItemFilterApiModel) HasSourceTypes() bool {
	if o != nil && !IsNil(o.SourceTypes) {
		return true
	}

	return false
}

// SetSourceTypes gets a reference to the given []WorkItemSourceTypeModel and assigns it to the SourceTypes field.
func (o *WorkItemFilterApiModel) SetSourceTypes(v []WorkItemSourceTypeModel) {
	o.SourceTypes = v
}

// GetTypes returns the Types field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkItemFilterApiModel) GetTypes() []WorkItemTypeModel {
	if o == nil {
		var ret []WorkItemTypeModel
		return ret
	}
	return o.Types
}

// GetTypesOk returns a tuple with the Types field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkItemFilterApiModel) GetTypesOk() ([]WorkItemTypeModel, bool) {
	if o == nil || IsNil(o.Types) {
		return nil, false
	}
	return o.Types, true
}

// HasTypes returns a boolean if a field has been set.
func (o *WorkItemFilterApiModel) HasTypes() bool {
	if o != nil && !IsNil(o.Types) {
		return true
	}

	return false
}

// SetTypes gets a reference to the given []WorkItemTypeModel and assigns it to the Types field.
func (o *WorkItemFilterApiModel) SetTypes(v []WorkItemTypeModel) {
	o.Types = v
}

// GetDuration returns the Duration field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkItemFilterApiModel) GetDuration() Int32RangeSelectorModel {
	if o == nil || IsNil(o.Duration.Get()) {
		var ret Int32RangeSelectorModel
		return ret
	}
	return *o.Duration.Get()
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkItemFilterApiModel) GetDurationOk() (*Int32RangeSelectorModel, bool) {
	if o == nil {
		return nil, false
	}
	return o.Duration.Get(), o.Duration.IsSet()
}

// HasDuration returns a boolean if a field has been set.
func (o *WorkItemFilterApiModel) HasDuration() bool {
	if o != nil && o.Duration.IsSet() {
		return true
	}

	return false
}

// SetDuration gets a reference to the given NullableInt32RangeSelectorModel and assigns it to the Duration field.
func (o *WorkItemFilterApiModel) SetDuration(v Int32RangeSelectorModel) {
	o.Duration.Set(&v)
}
// SetDurationNil sets the value for Duration to be an explicit nil
func (o *WorkItemFilterApiModel) SetDurationNil() {
	o.Duration.Set(nil)
}

// UnsetDuration ensures that no value is present for Duration, not even an explicit nil
func (o *WorkItemFilterApiModel) UnsetDuration() {
	o.Duration.Unset()
}

// GetIsAutomated returns the IsAutomated field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkItemFilterApiModel) GetIsAutomated() bool {
	if o == nil || IsNil(o.IsAutomated.Get()) {
		var ret bool
		return ret
	}
	return *o.IsAutomated.Get()
}

// GetIsAutomatedOk returns a tuple with the IsAutomated field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkItemFilterApiModel) GetIsAutomatedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsAutomated.Get(), o.IsAutomated.IsSet()
}

// HasIsAutomated returns a boolean if a field has been set.
func (o *WorkItemFilterApiModel) HasIsAutomated() bool {
	if o != nil && o.IsAutomated.IsSet() {
		return true
	}

	return false
}

// SetIsAutomated gets a reference to the given NullableBool and assigns it to the IsAutomated field.
func (o *WorkItemFilterApiModel) SetIsAutomated(v bool) {
	o.IsAutomated.Set(&v)
}
// SetIsAutomatedNil sets the value for IsAutomated to be an explicit nil
func (o *WorkItemFilterApiModel) SetIsAutomatedNil() {
	o.IsAutomated.Set(nil)
}

// UnsetIsAutomated ensures that no value is present for IsAutomated, not even an explicit nil
func (o *WorkItemFilterApiModel) UnsetIsAutomated() {
	o.IsAutomated.Unset()
}

// GetTags returns the Tags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkItemFilterApiModel) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkItemFilterApiModel) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *WorkItemFilterApiModel) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *WorkItemFilterApiModel) SetTags(v []string) {
	o.Tags = v
}

// GetExcludeTags returns the ExcludeTags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkItemFilterApiModel) GetExcludeTags() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.ExcludeTags
}

// GetExcludeTagsOk returns a tuple with the ExcludeTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkItemFilterApiModel) GetExcludeTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.ExcludeTags) {
		return nil, false
	}
	return o.ExcludeTags, true
}

// HasExcludeTags returns a boolean if a field has been set.
func (o *WorkItemFilterApiModel) HasExcludeTags() bool {
	if o != nil && !IsNil(o.ExcludeTags) {
		return true
	}

	return false
}

// SetExcludeTags gets a reference to the given []string and assigns it to the ExcludeTags field.
func (o *WorkItemFilterApiModel) SetExcludeTags(v []string) {
	o.ExcludeTags = v
}

// GetAutoTestIds returns the AutoTestIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WorkItemFilterApiModel) GetAutoTestIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.AutoTestIds
}

// GetAutoTestIdsOk returns a tuple with the AutoTestIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkItemFilterApiModel) GetAutoTestIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.AutoTestIds) {
		return nil, false
	}
	return o.AutoTestIds, true
}

// HasAutoTestIds returns a boolean if a field has been set.
func (o *WorkItemFilterApiModel) HasAutoTestIds() bool {
	if o != nil && !IsNil(o.AutoTestIds) {
		return true
	}

	return false
}

// SetAutoTestIds gets a reference to the given []string and assigns it to the AutoTestIds field.
func (o *WorkItemFilterApiModel) SetAutoTestIds(v []string) {
	o.AutoTestIds = v
}

func (o WorkItemFilterApiModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkItemFilterApiModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.NameOrId.IsSet() {
		toSerialize["nameOrId"] = o.NameOrId.Get()
	}
	if o.IncludeIds != nil {
		toSerialize["includeIds"] = o.IncludeIds
	}
	if o.ExcludeIds != nil {
		toSerialize["excludeIds"] = o.ExcludeIds
	}
	if o.ProjectIds != nil {
		toSerialize["projectIds"] = o.ProjectIds
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.Ids != nil {
		toSerialize["ids"] = o.Ids
	}
	if o.GlobalIds != nil {
		toSerialize["globalIds"] = o.GlobalIds
	}
	if o.Attributes != nil {
		toSerialize["attributes"] = o.Attributes
	}
	if o.IsDeleted.IsSet() {
		toSerialize["isDeleted"] = o.IsDeleted.Get()
	}
	if o.SectionIds != nil {
		toSerialize["sectionIds"] = o.SectionIds
	}
	if o.States != nil {
		toSerialize["states"] = o.States
	}
	if o.Priorities != nil {
		toSerialize["priorities"] = o.Priorities
	}
	if o.SourceTypes != nil {
		toSerialize["sourceTypes"] = o.SourceTypes
	}
	if o.Types != nil {
		toSerialize["types"] = o.Types
	}
	if o.Duration.IsSet() {
		toSerialize["duration"] = o.Duration.Get()
	}
	if o.IsAutomated.IsSet() {
		toSerialize["isAutomated"] = o.IsAutomated.Get()
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	if o.ExcludeTags != nil {
		toSerialize["excludeTags"] = o.ExcludeTags
	}
	if o.AutoTestIds != nil {
		toSerialize["autoTestIds"] = o.AutoTestIds
	}
	return toSerialize, nil
}

type NullableWorkItemFilterApiModel struct {
	value *WorkItemFilterApiModel
	isSet bool
}

func (v NullableWorkItemFilterApiModel) Get() *WorkItemFilterApiModel {
	return v.value
}

func (v *NullableWorkItemFilterApiModel) Set(val *WorkItemFilterApiModel) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkItemFilterApiModel) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkItemFilterApiModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkItemFilterApiModel(val *WorkItemFilterApiModel) *NullableWorkItemFilterApiModel {
	return &NullableWorkItemFilterApiModel{value: val, isSet: true}
}

func (v NullableWorkItemFilterApiModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkItemFilterApiModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


