/*
API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: adapters
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package adaptersapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GlobalCustomAttributePostApiModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GlobalCustomAttributePostApiModel{}

// GlobalCustomAttributePostApiModel struct for GlobalCustomAttributePostApiModel
type GlobalCustomAttributePostApiModel struct {
	// Name of attribute
	Name string `json:"name"`
	// Indicates whether the attribute is available
	IsEnabled NullableBool `json:"isEnabled,omitempty"`
	// Indicates whether the attribute value is mandatory to specify
	IsRequired NullableBool `json:"isRequired,omitempty"`
	// Collection of attribute options   Available for attributes of type `options` and `multiple options` only
	Options []CustomAttributeOptionPostApiModel `json:"options,omitempty"`
	// Type of attribute
	Type CustomAttributeType `json:"type"`
}

type _GlobalCustomAttributePostApiModel GlobalCustomAttributePostApiModel

// NewGlobalCustomAttributePostApiModel instantiates a new GlobalCustomAttributePostApiModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGlobalCustomAttributePostApiModel(name string, type_ CustomAttributeType) *GlobalCustomAttributePostApiModel {
	this := GlobalCustomAttributePostApiModel{}
	this.Name = name
	this.Type = type_
	return &this
}

// NewGlobalCustomAttributePostApiModelWithDefaults instantiates a new GlobalCustomAttributePostApiModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGlobalCustomAttributePostApiModelWithDefaults() *GlobalCustomAttributePostApiModel {
	this := GlobalCustomAttributePostApiModel{}
	return &this
}

// GetName returns the Name field value
func (o *GlobalCustomAttributePostApiModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GlobalCustomAttributePostApiModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GlobalCustomAttributePostApiModel) SetName(v string) {
	o.Name = v
}

// GetIsEnabled returns the IsEnabled field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GlobalCustomAttributePostApiModel) GetIsEnabled() bool {
	if o == nil || IsNil(o.IsEnabled.Get()) {
		var ret bool
		return ret
	}
	return *o.IsEnabled.Get()
}

// GetIsEnabledOk returns a tuple with the IsEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GlobalCustomAttributePostApiModel) GetIsEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsEnabled.Get(), o.IsEnabled.IsSet()
}

// HasIsEnabled returns a boolean if a field has been set.
func (o *GlobalCustomAttributePostApiModel) HasIsEnabled() bool {
	if o != nil && o.IsEnabled.IsSet() {
		return true
	}

	return false
}

// SetIsEnabled gets a reference to the given NullableBool and assigns it to the IsEnabled field.
func (o *GlobalCustomAttributePostApiModel) SetIsEnabled(v bool) {
	o.IsEnabled.Set(&v)
}
// SetIsEnabledNil sets the value for IsEnabled to be an explicit nil
func (o *GlobalCustomAttributePostApiModel) SetIsEnabledNil() {
	o.IsEnabled.Set(nil)
}

// UnsetIsEnabled ensures that no value is present for IsEnabled, not even an explicit nil
func (o *GlobalCustomAttributePostApiModel) UnsetIsEnabled() {
	o.IsEnabled.Unset()
}

// GetIsRequired returns the IsRequired field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GlobalCustomAttributePostApiModel) GetIsRequired() bool {
	if o == nil || IsNil(o.IsRequired.Get()) {
		var ret bool
		return ret
	}
	return *o.IsRequired.Get()
}

// GetIsRequiredOk returns a tuple with the IsRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GlobalCustomAttributePostApiModel) GetIsRequiredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsRequired.Get(), o.IsRequired.IsSet()
}

// HasIsRequired returns a boolean if a field has been set.
func (o *GlobalCustomAttributePostApiModel) HasIsRequired() bool {
	if o != nil && o.IsRequired.IsSet() {
		return true
	}

	return false
}

// SetIsRequired gets a reference to the given NullableBool and assigns it to the IsRequired field.
func (o *GlobalCustomAttributePostApiModel) SetIsRequired(v bool) {
	o.IsRequired.Set(&v)
}
// SetIsRequiredNil sets the value for IsRequired to be an explicit nil
func (o *GlobalCustomAttributePostApiModel) SetIsRequiredNil() {
	o.IsRequired.Set(nil)
}

// UnsetIsRequired ensures that no value is present for IsRequired, not even an explicit nil
func (o *GlobalCustomAttributePostApiModel) UnsetIsRequired() {
	o.IsRequired.Unset()
}

// GetOptions returns the Options field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GlobalCustomAttributePostApiModel) GetOptions() []CustomAttributeOptionPostApiModel {
	if o == nil {
		var ret []CustomAttributeOptionPostApiModel
		return ret
	}
	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GlobalCustomAttributePostApiModel) GetOptionsOk() ([]CustomAttributeOptionPostApiModel, bool) {
	if o == nil || IsNil(o.Options) {
		return nil, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *GlobalCustomAttributePostApiModel) HasOptions() bool {
	if o != nil && !IsNil(o.Options) {
		return true
	}

	return false
}

// SetOptions gets a reference to the given []CustomAttributeOptionPostApiModel and assigns it to the Options field.
func (o *GlobalCustomAttributePostApiModel) SetOptions(v []CustomAttributeOptionPostApiModel) {
	o.Options = v
}

// GetType returns the Type field value
func (o *GlobalCustomAttributePostApiModel) GetType() CustomAttributeType {
	if o == nil {
		var ret CustomAttributeType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GlobalCustomAttributePostApiModel) GetTypeOk() (*CustomAttributeType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GlobalCustomAttributePostApiModel) SetType(v CustomAttributeType) {
	o.Type = v
}

func (o GlobalCustomAttributePostApiModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GlobalCustomAttributePostApiModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if o.IsEnabled.IsSet() {
		toSerialize["isEnabled"] = o.IsEnabled.Get()
	}
	if o.IsRequired.IsSet() {
		toSerialize["isRequired"] = o.IsRequired.Get()
	}
	if o.Options != nil {
		toSerialize["options"] = o.Options
	}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *GlobalCustomAttributePostApiModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGlobalCustomAttributePostApiModel := _GlobalCustomAttributePostApiModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGlobalCustomAttributePostApiModel)

	if err != nil {
		return err
	}

	*o = GlobalCustomAttributePostApiModel(varGlobalCustomAttributePostApiModel)

	return err
}

type NullableGlobalCustomAttributePostApiModel struct {
	value *GlobalCustomAttributePostApiModel
	isSet bool
}

func (v NullableGlobalCustomAttributePostApiModel) Get() *GlobalCustomAttributePostApiModel {
	return v.value
}

func (v *NullableGlobalCustomAttributePostApiModel) Set(val *GlobalCustomAttributePostApiModel) {
	v.value = val
	v.isSet = true
}

func (v NullableGlobalCustomAttributePostApiModel) IsSet() bool {
	return v.isSet
}

func (v *NullableGlobalCustomAttributePostApiModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGlobalCustomAttributePostApiModel(val *GlobalCustomAttributePostApiModel) *NullableGlobalCustomAttributePostApiModel {
	return &NullableGlobalCustomAttributePostApiModel{value: val, isSet: true}
}

func (v NullableGlobalCustomAttributePostApiModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGlobalCustomAttributePostApiModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


