/*
API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: adapters
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package adaptersapi

import (
	"encoding/json"
)

// checks if the CustomAttributeSearchApiModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomAttributeSearchApiModel{}

// CustomAttributeSearchApiModel struct for CustomAttributeSearchApiModel
type CustomAttributeSearchApiModel struct {
	// Name of attribute
	Name NullableString `json:"name,omitempty"`
	// Unique IDs of projects where attribute is in use
	ProjectIds []string `json:"projectIds,omitempty"`
	// Unique IDs of attributes for search restriction
	CustomAttributeIds []string `json:"customAttributeIds,omitempty"`
	// Collection of attribute types
	CustomAttributeTypes []CustomAttributeType `json:"customAttributeTypes,omitempty"`
	// Indicates whether the attribute is available across all projects
	IsGlobal NullableBool `json:"isGlobal,omitempty"`
	// Indicates whether the attribute is deleted
	IsDeleted NullableBool `json:"isDeleted,omitempty"`
}

// NewCustomAttributeSearchApiModel instantiates a new CustomAttributeSearchApiModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomAttributeSearchApiModel() *CustomAttributeSearchApiModel {
	this := CustomAttributeSearchApiModel{}
	return &this
}

// NewCustomAttributeSearchApiModelWithDefaults instantiates a new CustomAttributeSearchApiModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomAttributeSearchApiModelWithDefaults() *CustomAttributeSearchApiModel {
	this := CustomAttributeSearchApiModel{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomAttributeSearchApiModel) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomAttributeSearchApiModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *CustomAttributeSearchApiModel) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *CustomAttributeSearchApiModel) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *CustomAttributeSearchApiModel) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *CustomAttributeSearchApiModel) UnsetName() {
	o.Name.Unset()
}

// GetProjectIds returns the ProjectIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomAttributeSearchApiModel) GetProjectIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.ProjectIds
}

// GetProjectIdsOk returns a tuple with the ProjectIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomAttributeSearchApiModel) GetProjectIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.ProjectIds) {
		return nil, false
	}
	return o.ProjectIds, true
}

// HasProjectIds returns a boolean if a field has been set.
func (o *CustomAttributeSearchApiModel) HasProjectIds() bool {
	if o != nil && !IsNil(o.ProjectIds) {
		return true
	}

	return false
}

// SetProjectIds gets a reference to the given []string and assigns it to the ProjectIds field.
func (o *CustomAttributeSearchApiModel) SetProjectIds(v []string) {
	o.ProjectIds = v
}

// GetCustomAttributeIds returns the CustomAttributeIds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomAttributeSearchApiModel) GetCustomAttributeIds() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.CustomAttributeIds
}

// GetCustomAttributeIdsOk returns a tuple with the CustomAttributeIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomAttributeSearchApiModel) GetCustomAttributeIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.CustomAttributeIds) {
		return nil, false
	}
	return o.CustomAttributeIds, true
}

// HasCustomAttributeIds returns a boolean if a field has been set.
func (o *CustomAttributeSearchApiModel) HasCustomAttributeIds() bool {
	if o != nil && !IsNil(o.CustomAttributeIds) {
		return true
	}

	return false
}

// SetCustomAttributeIds gets a reference to the given []string and assigns it to the CustomAttributeIds field.
func (o *CustomAttributeSearchApiModel) SetCustomAttributeIds(v []string) {
	o.CustomAttributeIds = v
}

// GetCustomAttributeTypes returns the CustomAttributeTypes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomAttributeSearchApiModel) GetCustomAttributeTypes() []CustomAttributeType {
	if o == nil {
		var ret []CustomAttributeType
		return ret
	}
	return o.CustomAttributeTypes
}

// GetCustomAttributeTypesOk returns a tuple with the CustomAttributeTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomAttributeSearchApiModel) GetCustomAttributeTypesOk() ([]CustomAttributeType, bool) {
	if o == nil || IsNil(o.CustomAttributeTypes) {
		return nil, false
	}
	return o.CustomAttributeTypes, true
}

// HasCustomAttributeTypes returns a boolean if a field has been set.
func (o *CustomAttributeSearchApiModel) HasCustomAttributeTypes() bool {
	if o != nil && !IsNil(o.CustomAttributeTypes) {
		return true
	}

	return false
}

// SetCustomAttributeTypes gets a reference to the given []CustomAttributeType and assigns it to the CustomAttributeTypes field.
func (o *CustomAttributeSearchApiModel) SetCustomAttributeTypes(v []CustomAttributeType) {
	o.CustomAttributeTypes = v
}

// GetIsGlobal returns the IsGlobal field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomAttributeSearchApiModel) GetIsGlobal() bool {
	if o == nil || IsNil(o.IsGlobal.Get()) {
		var ret bool
		return ret
	}
	return *o.IsGlobal.Get()
}

// GetIsGlobalOk returns a tuple with the IsGlobal field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomAttributeSearchApiModel) GetIsGlobalOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsGlobal.Get(), o.IsGlobal.IsSet()
}

// HasIsGlobal returns a boolean if a field has been set.
func (o *CustomAttributeSearchApiModel) HasIsGlobal() bool {
	if o != nil && o.IsGlobal.IsSet() {
		return true
	}

	return false
}

// SetIsGlobal gets a reference to the given NullableBool and assigns it to the IsGlobal field.
func (o *CustomAttributeSearchApiModel) SetIsGlobal(v bool) {
	o.IsGlobal.Set(&v)
}
// SetIsGlobalNil sets the value for IsGlobal to be an explicit nil
func (o *CustomAttributeSearchApiModel) SetIsGlobalNil() {
	o.IsGlobal.Set(nil)
}

// UnsetIsGlobal ensures that no value is present for IsGlobal, not even an explicit nil
func (o *CustomAttributeSearchApiModel) UnsetIsGlobal() {
	o.IsGlobal.Unset()
}

// GetIsDeleted returns the IsDeleted field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomAttributeSearchApiModel) GetIsDeleted() bool {
	if o == nil || IsNil(o.IsDeleted.Get()) {
		var ret bool
		return ret
	}
	return *o.IsDeleted.Get()
}

// GetIsDeletedOk returns a tuple with the IsDeleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomAttributeSearchApiModel) GetIsDeletedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsDeleted.Get(), o.IsDeleted.IsSet()
}

// HasIsDeleted returns a boolean if a field has been set.
func (o *CustomAttributeSearchApiModel) HasIsDeleted() bool {
	if o != nil && o.IsDeleted.IsSet() {
		return true
	}

	return false
}

// SetIsDeleted gets a reference to the given NullableBool and assigns it to the IsDeleted field.
func (o *CustomAttributeSearchApiModel) SetIsDeleted(v bool) {
	o.IsDeleted.Set(&v)
}
// SetIsDeletedNil sets the value for IsDeleted to be an explicit nil
func (o *CustomAttributeSearchApiModel) SetIsDeletedNil() {
	o.IsDeleted.Set(nil)
}

// UnsetIsDeleted ensures that no value is present for IsDeleted, not even an explicit nil
func (o *CustomAttributeSearchApiModel) UnsetIsDeleted() {
	o.IsDeleted.Unset()
}

func (o CustomAttributeSearchApiModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomAttributeSearchApiModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.ProjectIds != nil {
		toSerialize["projectIds"] = o.ProjectIds
	}
	if o.CustomAttributeIds != nil {
		toSerialize["customAttributeIds"] = o.CustomAttributeIds
	}
	if o.CustomAttributeTypes != nil {
		toSerialize["customAttributeTypes"] = o.CustomAttributeTypes
	}
	if o.IsGlobal.IsSet() {
		toSerialize["isGlobal"] = o.IsGlobal.Get()
	}
	if o.IsDeleted.IsSet() {
		toSerialize["isDeleted"] = o.IsDeleted.Get()
	}
	return toSerialize, nil
}

type NullableCustomAttributeSearchApiModel struct {
	value *CustomAttributeSearchApiModel
	isSet bool
}

func (v NullableCustomAttributeSearchApiModel) Get() *CustomAttributeSearchApiModel {
	return v.value
}

func (v *NullableCustomAttributeSearchApiModel) Set(val *CustomAttributeSearchApiModel) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomAttributeSearchApiModel) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomAttributeSearchApiModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomAttributeSearchApiModel(val *CustomAttributeSearchApiModel) *NullableCustomAttributeSearchApiModel {
	return &NullableCustomAttributeSearchApiModel{value: val, isSet: true}
}

func (v NullableCustomAttributeSearchApiModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomAttributeSearchApiModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


